### ISSUE TITLE
[osx64] The app window is transparent and with no CSS

### ISSUE THREAD

**Issue by Zorgatone** [Atraci/Atraci-Angular#12]
I built the app as described in the README.md. I noticed the app wasn't loading correctly, and the window was transparent and without CSS styles.

I opened the nwjs executable packaged in the .app directly to see this error:

	TR:MacOS tommaso$ ./nwjs
	[5807:0811/093019:ERROR:nw_shell.cc(324)] Error: [$injector:modulerr] http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=AtraciApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.8%2F%24injector%2Fnomod%3Fp0%3DAtraciApp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A6%3A416%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A366%0A%20%20%20%20at%20a%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A7)%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A250%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A35%3A424%0A%20%20%20%20at%20s%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A7%3A302)%0A%20%20%20%20at%20g%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A35%3A202)%0A%20%20%20%20at%20Ob%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A38%3A435)%0A%20%20%20%20at%20d%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A17%3A350)
	    at Error (native)
	    at file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:6:416
	    at file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:36:98
	    at s (file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:7:302)
	    at g (file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:35:202)
	    at Ob (file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:38:435)
	    at d (file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:17:350)
	    at sc (file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:18:153)
	    at Jd (file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:16:483)
	    at file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js:249:412
	[5807:0811/093019:INFO:CONSOLE(36)] "Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=AtraciApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.8%2F%24injector%2Fnomod%3Fp0%3DAtraciApp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A6%3A416%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A366%0A%20%20%20%20at%20a%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A7)%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A250%0A%20%20%20%20at%20file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A35%3A424%0A%20%20%20%20at%20s%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A7%3A302)%0A%20%20%20%20at%20g%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A35%3A202)%0A%20%20%20%20at%20Ob%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A38%3A435)%0A%20%20%20%20at%20d%20(file%3A%2F%2F%2FApplications%2FAtraci.app%2FContents%2FResources%2Fapp.nw%2Fnode_modules%2Fangular%2Fangular.min.js%3A17%3A350)", source: file:///Applications/Atraci.app/Contents/Resources/app.nw/node_modules/angular/angular.min.js (36)

**Comment by JMartelot** [comment]
Hi Zorgatone,

I have the same problem, did you find a solution ?

**Comment by Zorgatone** [comment]
No I didn't look into that much

Il martedì 8 settembre 2015, Jean Martelot <notifications@github.com> ha
scritto:

> Hi Zorgatone,
>
> I have the same problem, did you find a solution ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Atraci/Atraci-Angular/issues/12#issuecomment-138691052>
> .
>


-- 
Inviato da Gmail Mobile

**Comment by durimjusaj** [comment]
I had the same problem. Reinstalling modules fix this for me. Have you tried this ?  And have you called gulp buildFirst ?

**Comment by JMartelot** [comment]
Ok, I'll see if reinstalling modules fix this. Yes I have called gulp buildFirst.
