### ISSUE TITLE
Error with node-sass

### ISSUE THREAD

**Issue by Airon90** [Atraci/Atraci-Angular#8]
Hi, I'm using latest Arch Linux and I got problem with compiling Atraci-Angular.
I followed the instructions in README.md but at point 3 I got problems:

```[airon@aironpc Atraci-Angular-master]$ sudo npm install
-
> node-sass@1.2.3 install /home/airon/Scaricati/Atraci-Angular-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/airon/Scaricati/Atraci-Angular-master/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /home/airon/Scaricati/Atraci-Angular-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/airon/Scaricati/Atraci-Angular-master/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Linux 3.19.0-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/airon/Scaricati/Atraci-Angular-master/npm-debug.log
```

And the npm-debug.log file is here: https://gist.github.com/Airon90/d452e000b7b502fe8410

**Comment by shyne99** [comment]
Hello,

why is he trying to install 1.2.3 when the package.json file require 1.2.4 ?? 
Your error came from here, 1.2.3 is broken now.

You can also try to install it explicitly, by running
* npm install gulp-sass@1.2.4

**Comment by Airon90** [comment]
I think that is a bug related to Arch Linux:

```
[airon@aironpc ~]$ sudo npm install gulp-sass@1.2.4
[sudo] password di root: 
|
> node-sass@1.2.3 install /home/airon/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/airon/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /home/airon/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/airon/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Linux 3.19.0-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "gulp-sass@1.2.4"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/airon/npm-debug.log
```

**Comment by gutierri** [comment]
@Airon90 Yes! In Arch Linux does not work :(

**Comment by shiddy** [comment]
I was getting the same error running OSX 10.10.4 with node-sass 1.2.3 as well.

things seemed to run swimmingly after forcing npm install with node-sass 1.2.2

ie `npm install node-sass@1.2.2`

:+1:
